name: 'Semantic release'
description: 'Version affected projects, dry run if PR'
runs:
  using: 'composite'
  steps:
    # Prepare releases

    - uses: ./.github/actions/git-set-user

    # Resolve semantic release args

    - name: Resolve Semantic Release args
      id: resolve-semantic-release-args
      shell: bash
      run: |
        ARGS=""
        if [ "${{ github.event.pull_request.base.ref }}" == "main" ]; then ARGS="--dry-run"; fi;
        echo "::set-output name=release-args::${ARGS}"

    # Dry runs releases

    - shell: bash
      run: npx nx affected --target=version ${{ steps.resolve-semantic-release-args.outputs.release-args }}
      env:
        NX_CLOUD_DISTRIBUTED_EXECUTION: 'false'
