name: 'Setup Docker for GitHub Actions'
description: 'Setup Docker for GitHub Actions'
runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
