name: Setup Node from nvmrc
description: Setup Node from nvmrc
runs:
  using: composite
  steps:
    - name: Read .nvmrc
      shell: bash
      run: echo "##set-output name=node-version::$(cat .nvmrc)"
      id: nvm
    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v2
      with:
        node-version: '${{ steps.nvm.outputs.node-version }}'
