name: CI
on: [pull_request]
env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

jobs:
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: ./.github/actions/setup-node
      - run: yarn install --frozen-lockfile
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=lint --parallel
      - run: npx nx affected --target=test --parallel
      - run: npx nx affected --target=build --configuration production --parallel
      - run: npx nx-cloud stop-all-agents

  agents:
    runs-on: ubuntu-latest
    name: nx cloud agents
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: ./.github/actions/setup-node
      - run: yarn install --frozen-lockfile
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
