name: Quality Assurance
on: [pull_request]

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  DOCKER_REGISTRY: ghcr.io
  DOCKER_NAMESPACE: ${{ github.repository }}

concurrency:
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - uses: ./.github/actions/node-setup
      - uses: ./.github/actions/docker-setup
      - name: Log in to the Container registry
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ADMIN_PAT }}

      - run: yarn install --frozen-lockfile
      - run: npx nx-cloud start-ci-run
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel
      - run: npx nx affected --target=test --parallel
      - uses: ./.github/actions/nx-semantic-release
      - run: npx nx affected --target=build --configuration production --parallel
      - run: npx nx affected --target=docker --configuration production --parallel
        if: ${{ github.actor != 'dependabot[bot]' }}
        env:
          NX_CLOUD_DISTRIBUTED_EXECUTION: 'false'
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npx nx-cloud stop-all-agents
        if: ${{ always() }}
      - run: ./trunk check --no-progress

  agents:
    runs-on: ubuntu-latest
    name: nx cloud agents
    timeout-minutes: 10
    strategy:
      matrix:
        agent: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: ./.github/actions/node-setup
      - run: yarn install --frozen-lockfile
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
