name: CI
on:
  push:
    branches:
      - main

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

concurrency:
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # Set an ADMIN PAT in order to be able to push tags later on
          token: ${{ secrets.ADMIN_PAT }}
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: ./.github/actions/setup-node
      - run: yarn install --frozen-lockfile
      - run: npx nx-cloud start-ci-run
      - uses: ./.github/actions/semantic-release
      - run: npx nx affected --target=build --configuration production --parallel
      - run: npx nx-cloud stop-all-agents
      - uses: ./.github/actions/push-protected
        with:
          branch: ${{ env.NX_BRANCH }}
          github-token: ${{ secrets.ADMIN_PAT }}

  agents:
    runs-on: ubuntu-latest
    name: nx cloud agents
    timeout-minutes: 10
    strategy:
      matrix:
        agent: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: ./.github/actions/setup-node
      - run: yarn install --frozen-lockfile
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
