name: Staging
on:
  push:
    tags: ['*']

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  DOCKER_REGISTRY: ghcr.io
  DOCKER_NAMESPACE: ${{ github.repository }}

jobs:
  publish-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_PAT }}

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - uses: ./.github/actions/node-setup

      - uses: ./.github/actions/docker-setup
      - name: Log in to the Container registry
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ADMIN_PAT }}

      - run: yarn install --frozen-lockfile

      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=build --configuration production --parallel
      - run: npx nx affected --target=docker --configuration production --parallel
        env:
          NX_CLOUD_DISTRIBUTED_EXECUTION: 'false'
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/git-set-user
      - run: npx nx affected --target=pages --configuration production --parallel
        env:
          NX_CLOUD_DISTRIBUTED_EXECUTION: 'false'
      - run: npx nx-cloud stop-all-agents
        if: ${{ always() }}

  agents:
    runs-on: ubuntu-latest
    name: nx cloud agents
    timeout-minutes: 10
    strategy:
      matrix:
        agent: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - uses: ./.github/actions/node-setup

      - uses: ./.github/actions/docker-setup
      - name: Log in to the Container registry
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ADMIN_PAT }}

      - run: yarn install --frozen-lockfile
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
